[package]
name = "anime-torrent-info"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
paste = "1.0.12"
regex = "1.7.3"
typed-builder = "0.14.0"
